[debug]
logLevel = "info"
flushLevel = "trace"
profile = false

[frame]
initDelay = 0
step = 0

[tremor]
# linear, smoothstep, softcore, cubic
method = "linear"
# Contolls falloff this is the scale at which falloff=50%
halfScale = 0.91
# Controls the power at min/max scale
powerAtMin = 0.0
powerAtMax = 8.25
# Min/max scale points, this is just used for the powerAt dosen't min actual min/max
maxScale = 30.0
minScale = 0.0
