[sounds]
lFootstepL = "GTS.esp|1E93AB"
lFootstepR = "GTS.esp|1E93AD"
lJumpLand = "GTS.esp|183F43"
xlFootstepL = "GTS.esp|271EF4"
xlFootstepR = "GTS.esp|271EF4"
xlRumbleL = "GTS.esp|36A06D"
xlRumbleR = "GTS.esp|36A06D"
xlSprintL = "GTS.esp|319060"
xlSprintR = "GTS.esp|319060"
xxlFootstepL = "GTS.esp|16FB25"
xxlFootstepR = "GTS.esp|16FB25"
growthSound = "GTS.esp|271EF6"
shrinkSound = "GTS.esp|364F6A"
GreybeardRumble = "GTS.esp|1CAD96"
MoanSound = "GTS.esp|09B0AC"
LaughSound_Type1 = "GTS.esp|09B0A9"
LaughSound_Type2 = "GTS.esp|5D3B5B"
BloodGushSound = "Skyrim.esm|10F78C"
VoreSound_Success = "Skyrim.esm|10FAE5"
VoreSound_Fail = "Skyrim.esm|000F8B"
GtsCrushSound = "GTS.esp|01102F"
GtsFallSound = "GTS.esp|183F43"
ClothTearSound = "GTS.esp|30EE54"
RumbleWalkSound = "GTS.esp|50423E"
GiantImpactSound = "Skyrim.esm|0C52F7"
VoreSwallow = "GTS.esp|56E747"
TriggerHG = "GTS.esp|578948"
ThighSandwichImpact = "GTS.esp|582B49"
HeavyStompSound = "GTS.esp|596F4E"
ShrinkToNothingSound = "GTS.esp|5BA659"
CrunchImpactSound = "GTS.esp|5D8C5C"
CrunchKillSound = "GTS.esp|5D8C5D"
BreastImpact = "GTS.esp|5E2E5F"
SoftHandAttack = "GTS.esp|5E2E60"
SwingImpact = "GTS.esp|68F0AD"

TinyCalamity_Impact = "GTS.esp|76DCD2"
TinyCalamity_Crush = "GTS.esp|76DCD3"
TinyCalamity_ReachedSpeed = "GTS.esp|7820D7"
TinyCalamity_AbsorbTiny = "GTS.esp|7B9BE6"
TinyCalamity_ReadyRune = "GTS.esp|7B9BE5"
TinyCalamity_SpawnRune = "GTS.esp|7B9BE4"

Magic_ProtectTinies = "GTS.esp|772DD4"
Magic_BreakTinyProtection = "GTS.esp|777ED6"

ShrinkOutburstSound = "GTS.esp|6524A3"
TinyCalamitySound = "GTS.esp|65C6AA"

HighHeel_x2 = "GTS.esp|615875"
HighHeel_x4 = "GTS.esp|615877"
HighHeel_x8 = "GTS.esp|615878"
HighHeel_x12 = "GTS.esp|615879"
HighHeel_x24 = "GTS.esp|61587A"
HighHeel_x48 = "GTS.esp|61587B"
HighHeel_x96 = "GTS.esp|61587C"
HighHeel_Mega = "GTS.esp|61587D"

HighHeelLand_x2 = "GTS.esp|61588E"
HighHeelLand_x4 = "GTS.esp|61588F"
HighHeelLand_x8 = "GTS.esp|615890"
HighHeelLand_x12 = "GTS.esp|615891"
HighHeelLand_x24 = "GTS.esp|615892"
HighHeelLand_x48 = "GTS.esp|615893"
HighHeelLand_x96 = "GTS.esp|615894"
HighHeelLand_Mega = "GTS.esp|615895"

Normal_x2 = "GTS.esp|61587E"
Normal_x4 = "GTS.esp|61587F"
Normal_x8 = "GTS.esp|615880"
Normal_x12 = "GTS.esp|615881"
Normal_x24 = "GTS.esp|615882"
Normal_x48 = "GTS.esp|615883"
Normal_x96 = "GTS.esp|615884"
Normal_Mega = "GTS.esp|615885"

NormalLand_x2 = "GTS.esp|615886"
NormalLand_x4 = "GTS.esp|615887"
NormalLand_x8 = "GTS.esp|615888"
NormalLand_x12 = "GTS.esp|615889"
NormalLand_x24 = "GTS.esp|61588A"
NormalLand_x48 = "GTS.esp|61588B"
NormalLand_x96 = "GTS.esp|61588C"
NormalLand_Mega = "GTS.esp|61588D"



[spellEffects]
SmallMassiveThreat = "GTS.esp|1A2568"
# Explosive
GrowthSpurt1 = "GTS.esp|007928"
GrowthSpurt2 = "GTS.esp|1E42A5"
GrowthSpurt3 = "GTS.esp|1E42A6"
# Shrink
ShrinkPCButton = "GTS.esp|10A6CF"
ShrinkBack = "GTS.esp|005369"
ShrinkBackNPC = "GTS.esp|00536C"
ShrinkSpell = "GTS.esp|002850"
ShrinkAlly = "GTS.esp|0058D1"
ShrinkAllyAdept = "GTS.esp|452F17"
ShrinkAllyExpert = "GTS.esp|452F18"
ShrinkEnemy = "GTS.esp|00387B"
ShrinkEnemyAOE = "GTS.esp|0DCDC5"
ShrinkEnemyAOEMast = "GTS.esp|0DCDCA"
ShrinkBolt = "GTS.esp|3C5278"
ShrinkStorm = "GTS.esp|3C527C"
# Grow
SwordEnchant = "GTS.esp|00FA9E"
EnchGigantism = "GTS.esp|3EDAC5"
ShrinkToNothing = "GTS.esp|009979"
SlowGrowth = "GTS.esp|019C3D"
SlowGrowth2H = "GTS.esp|086C8D"
GrowthSpell = "GTS.esp|0022EB"
GrowthSpellAdept = "GTS.esp|45D124"
GrowthSpellExpert = "GTS.esp|45D125"
GrowPcButton = "GTS.esp|002DB5"
GrowAlly = "GTS.esp|0058D5"
GrowAllyAdept = "GTS.esp|452F15"
GrowAllyExpert = "GTS.esp|452F16"
GrowAllySizeButton = "GTS.esp|123BE3"
ShrinkAllySizeButton = "GTS.esp|123BE4"
CrushGrowthMGEF = "GTS.esp|2028B6"

# Damage
SizeRelatedDamage0 = "GTS.esp|00A441"
SizeRelatedDamage1 = "GTS.esp|00A9A8"
SizeRelatedDamage2 = "GTS.esp|00B474"
# Absorb
AbsorbMGEF = "GTS.esp|00B470"
TrueAbsorb = "GTS.esp|22B0D5"
# Potions
EffectGrowthPotionWeak = "GTS.esp|3D4582"
EffectGrowthPotionNormal = "GTS.esp|7C8EFC"
EffectGrowthPotionStrong = "GTS.esp|7C8EFE"
EffectGrowthPotionExtreme = "GTS.esp|7C8F00"

SizeMasteryPotionBasic = "GTS.esp|7CE013"

ResistShrinkPotionWeak = "GTS.esp|3D4583"
ResistShrinkPotionNormal = "GTS.esp|7C8F09"
ResistShrinkPotionStrong = "GTS.esp|7C8F0A"
ResistShrinkPotionExtreme = "GTS.esp|7C8F0B"

EffectSizePotionWeak = "GTS.esp|3E38BB"
EffectSizePotionNormal = "GTS.esp|3E38BC"
EffectSizePotionStrong = "GTS.esp|3E38BD"
EffectSizePotionExtreme = "GTS.esp|3E38C0"
EffectSizeHungerPotion = "GTS.esp|42F7D6"
EffectSizeAmplifyPotion = "GTS.esp|452F1D"
SizeDrainPotion = "GTS.esp|5B5557"
ShrinkPoison = "GTS.esp|5B5552"

gtsProtectTiniesMGEF = "GTS.esp|763AD1"


# Crushing
FakeCrushEffect = "GTS.esp|271EF9"
HealthBoost = "GTS.esp|518645"




[spells]
GtsVoreFearSpell = "GTS.esp|026D15"
SmallMassiveThreatSpell = "GTS.esp|1A2566"
CrushGrowthSpell = "GTS.esp|2028B7"
TrueAbsorbSpell = "GTS.esp|22B0D6"
StartVoreFake = "GTS.esp|319056"
StartVore = "GTS.esp|31905C"
gtsSizeCloakSpellTiny = "GTS.esp|00CA0A"
gtsSizeCloakSpellSmall = "GTS.esp|00A9A5"
gtsSizeCloakSpellMedium = "GTS.esp|00CA07"
gtsSizeCloakSpellLarge = "GTS.esp|00CA08"
gtsSizeCloakSpellHuge = "GTS.esp|00CA0C"
gtsSizeCloakSpellMega = "GTS.esp|00CA0E"
gtsSizeCloakSpellMassive = "GTS.esp|08BD90"
gtsSizeCloakSpellGigantic = "GTS.esp|08BD92"
gtsSizeCloakSpellImpossible = "GTS.esp|08BD94"
ShrinkToNothingSpell = "GTS.esp|00997A"
FakeCrushSpell = "GTS.esp|271EF7"
ShrinkBackNPCSpell = "GTS.esp|00536B"
ShrinkBackSpell = "GTS.esp|005368"
GtsBleedSpell = "GTS.esp|01CEA2"
HealthBoost = "GTS.esp|518643"
ShrinkStorm = "GTS.esp|3C527A"
ShrinkBolt = "GTS.esp|3C5276"

gtsProtectTiniesSpell = "GTS.esp|763ACF"

# Survival

Survival_HungerStage0 = "ccQDRSSE001-SurvivalMode.esl|000876"
Survival_HungerStage1 = "ccQDRSSE001-SurvivalMode.esl|00087E"
Survival_HungerStage2 = "ccQDRSSE001-SurvivalMode.esl|000880"
Survival_HungerStage3 = "ccQDRSSE001-SurvivalMode.esl|000881"
Survival_HungerStage4 = "ccQDRSSE001-SurvivalMode.esl|000886"
Survival_HungerStage5 = "ccQDRSSE001-SurvivalMode.esl|000885"

[perks]
TalkToActor = "GTS.esp|5F7265"
BendLifeless = "GTS.esp|7913D9"
SmallMassiveThreatSizeSteal = "GTS.esp|2496E8"
VorePerk = "GTS.esp|355C68"
CalamityPerk = "GTS.esp|18E161"
EternalCalamity = "GTS.esp|5ED064"
MassVorePerk = "GTS.esp|462228"
GrowthOnHitPerk = "GTS.esp|30EE52"
AdditionalGrowth = "GTS.esp|151518"
AdditionalGrowth_p2 = "GTS.esp|67FDAC"
StaggerImmunity = "GTS.esp|0AA3B2"
FastShrink = "GTS.esp|16081F"
LethalShrink = "GTS.esp|160820"
ExtraGrowth = "GTS.esp|332563"
ExtraGrowthMax = "GTS.esp|397972"
HealthRegenPerk = "GTS.esp|18E160"
RandomGrowth = "GTS.esp|35AD69"
Gluttony = "GTS.esp|33C764"
SoulVorePerk = "GTS.esp|33C765"
GrowthDesirePerk = "GTS.esp|128CF6"
ColossalGrowth = "GTS.esp|128CF7"
NoSpeedLoss = "GTS.esp|2E663B"
SizeReserve = "GTS.esp|4204CE"
SizeReserveAug = "GTS.esp|4C7638"
BonusSpeedPerk = "GTS.esp|4255D0"
OnTheEdge = "GTS.esp|4399E3"
LethalSprint = "GTS.esp|123BEB"
hhBonus = "GTS.esp|271EF1"
GrowthOfStrength = "GTS.esp|151519"
LaunchPerk = "GTS.esp|1CAD91"
LaunchDamage = "GTS.esp|2496E9"
TrueGiantess = "GTS.esp|128CF4"

MightyLegs = "GTS.esp|123BE9"
SprintDamageMult1 = "GTS.esp|123BEA"
Cruelty = "GTS.esp|128CF8"
RealCruelty = "GTS.esp|142205"
BoneCrusher = "GTS.esp|128CF5"
HealthGate = "GTS.esp|4E0B39"
GrowingPressure = "GTS.esp|1E93A9"
DestructionBasics = "GTS.esp|587C4A"
KillerThighs = "GTS.esp|587C4B"

HugCrush = "GTS.esp|60656E"
HugCrush_Greed = "GTS.esp|606571"
HugCrush_ToughGrip = "GTS.esp|606570"
HugCrush_MightyCuddles = "GTS.esp|60656F"
HugCrush_HugsOfDeath = "GTS.esp|629C98"
HugCrush_LovingEmbrace = "GTS.esp|7598CE"

SkilledGTS = "GTS.esp|61A996"
DisastrousTremor = "GTS.esp|61FA97"

DarkArts = "GTS.esp|64319B"
DarkArts_Aug = "GTS.esp|64319C"
DarkArts_Aug2 = "GTS.esp|64319D"
DarkArts_Aug3 = "GTS.esp|19D462"
DarkArts_Max = "GTS.esp|63E09A"

ButtCrush_KillerBooty = "GTS.esp|5FC366"
ButtCrush_GrowingDisaster = "GTS.esp|5FC367"
ButtCrush_UnstableGrowth = "GTS.esp|5FC368"
ButtCrush_LoomingDoom = "GTS.esp|5FC369"
ButtCrush_NoEscape = "GTS.esp|5FC36A"

SizeAbsorption = "GTS.esp|610774"

MightOfGiants = "GTS.esp|6AD6B1"







[explosions]
BloodExplosion = "GTS.esp|01CE9D"
BloodFX = "Dawnguard.esm|00E7B4"
footstepExplosion = "GTS.esp|035C81"
draugrexplosion = "GTS.esp|035C80"
ShrinkOutburstExplosion = "GTS.esp|638F99"

[globals]
FreeLookOnVore = "GTS.esp|281206"
MultiplyGameModePC = "GTS.esp|47B72B"
MultiplyGameModeNPC = "GTS.esp|47B72C"
GtsDecideGrowth = "GTS.esp|15661D"
sizeLimit = "GTS.esp|2028B4"
AllowClothTearing = "GTS.esp|30EE55"
GtsNPCEffectImmunityToggle = "GTS.esp|271EFA"
GtsPCEffectImmunityToggle = "GTS.esp|4F4F3B"
ProgressionMultiplier = "GTS.esp|37E46E"
CrushGrowthRate = "GTS.esp|2028B9"
AccurateCellScan = "GTS.esp|1CAD98"
ChosenGameMode = "GTS.esp|2EB74C"
GrowthModeRate = "GTS.esp|2028C3"
ShrinkModeRate = "GTS.esp|2028C4"
AllowHitGrowth = "GTS.esp|485931"
AllowHitGrowthNPC = "GTS.esp|47662A"
AllowMoanSounds = "GTS.esp|48FB32"
CurseOfGrowthMaxSize = "GTS.esp|499D34"
RandomGrowthMultiplyPC = "GTS.esp|48592F"
RandomGrowthMultiplyNPC = "GTS.esp|485930"
ChosenGameModeNPC = "GTS.esp|2EB747"
GrowthModeRateNPC = "GTS.esp|2EB74B"
ShrinkModeRateNPC = "GTS.esp|2EB74A"
GlobalMaxSizeCalc = "GTS.esp|20CAC5"
GtsMassBasedSize = "GTS.esp|277005"
FollowersSizeLimit = "GTS.esp|48082D"
NPCSizeLimit = "GTS.esp|48082E"
SelectedSizeFormula = "GTS.esp|277004"
ProtectEssentials = "GTS.esp|23A3E2"
EnableGiantSounds = "GTS.esp|26CDF0"
PCAdditionalEffects = "GTS.esp|3D4586"
NPCSizeEffects = "GTS.esp|3D4587"
CrushGrowthStorage = "GTS.esp|3D4588"
ManualGrowthStorage = "GTS.esp|4162CB"
BalanceMode = "GTS.esp|42F7D3"

Cleavage_OffsetY = "GTS.esp|271EFF"
Cleavage_OffsetZ = "GTS.esp|142206"

FirstPersonMode = "GTS.esp|2B8D35"
ProneOffsetFP = "GTS.esp|2C2F38"
EnableCamera = "GTS.esp|290512"
CameraMode = "GTS.esp|290513"
FeetCamera = "GTS.esp|290525"
usingAutoDistance = "GTS.esp|290524"
ProneEnabled = "GTS.esp|2C8039"
MinDistance = "GTS.esp|29051E"
MaxDistance = "GTS.esp|29051F"
CameraZoomSpeed = "GTS.esp|290526"
CameraZoomPrecision = "GTS.esp|290527"
proneCameraX = "GTS.esp|290510"
proneCameraY = "GTS.esp|290511"
proneCombatCameraX = "GTS.esp|290514"
proneCombatCameraY = "GTS.esp|290515"
cameraX = "GTS.esp|29051A"
cameraY = "GTS.esp|29051B"
combatCameraX = "GTS.esp|29051D"
combatCameraY = "GTS.esp|29051C"
proneCameraAlternateX = "GTS.esp|290516"
proneCameraAlternateY = "GTS.esp|290517"
proneCombatCameraAlternateX = "GTS.esp|290518"
proneCombatCameraAlternateY = "GTS.esp|290519"
cameraAlternateX = "GTS.esp|290520"
cameraAlternateY = "GTS.esp|290521"
combatCameraAlternateX = "GTS.esp|290522"
combatCameraAlternateY = "GTS.esp|290523"
CalcProne = "GTS.esp|2D733A"
AllowTimeChange = "GTS.esp|277001"
bonusHPMultiplier = "GTS.esp|28B408"
bonusCarryWeightMultiplier = "GTS.esp|28B407"
bonusJumpHeightMultiplier = "GTS.esp|28B40A"
bonusDamageMultiplier = "GTS.esp|28B409"
bonusSpeedMultiplier = "GTS.esp|28B40B"
bonusSpeedMax = "GTS.esp|28B40C"
GtsEnableLooting = "GTS.esp|2EB748"
GtsNPCEnableLooting = "GTS.esp|2EB749"
NormalCameraTarget = "GTS.esp|4B8335"
AltCameraTarget = "GTS.esp|4B8336"

EnableColliders = "GTS.esp|42A6D2"
EnableDebugOverlay = "GTS.esp|42A6D1"

GtsSkillLevel = "GTS.esp|142200"
GtsSkillRatio = "GTS.esp|142202"
GtsSkillProgress = "GTS.esp|142201"

ConversationCameraComp = "GTS.esp|50933F"

LevelLimitModifier = "GTS.esp|151516"
SizeLossModifier = "GTS.esp|1E429E"

PreciseDamage = "GTS.esp|4F4F3A"
PreciseDamageOthers = "GTS.esp|513540"

HostileDamage = "GTS.esp|271EF2"

GtsSkillPerkPoints = "GTS.esp|2352E1"

# Survival Values

Survival_HungerNeedMaxValue = "ccQDRSSE001-SurvivalMode.esl|00080C"
Survival_HungerNeedValue = "ccQDRSSE001-SurvivalMode.esl|00081A"

# Survival stages
Survival_HungerStage1Value = "ccQDRSSE001-SurvivalMode.esl|000806"
Survival_HungerStage2Value = "ccQDRSSE001-SurvivalMode.esl|000802"
Survival_HungerStage3Value = "ccQDRSSE001-SurvivalMode.esl|000803"
Survival_HungerStage4Value = "ccQDRSSE001-SurvivalMode.esl|000804"
Survival_HungerStage5Value = "ccQDRSSE001-SurvivalMode.esl|000805"
# Toggle
Survival_ModeEnabled = "ccQDRSSE001-SurvivalMode.esl|000826"

[quests]
MainQuest = "GTS.esp|005E3A"
ManagerQuest = "GTS.esp|000D62"

[factions]
FollowerFaction = "Skyrim.esm|084D1B"
DwarwenAutomatonFaction = "Skyrim.esm|043598"
DraugrFaction = "Skyrim.esm|02430D"

[impacts]
GtsBloodSprayImpactSet = "GTS.esp|01CEA7"
GtsBloodSprayImpactSetVore = "GTS.esp|024578"
GtsBloodSprayImpactSetVoreMedium = "GTS.esp|024579"
GtsBloodSprayImpactSetVoreSmallest = "GTS.esp|02457A"

[races]
dragonRace = "Skyrim.esm|012E82"
FrostbiteSpiderRace = "Skyrim.esm|0131F8"
FrostbiteSpiderRaceGiant = "Skyrim.esm|04E507"
FrostbiteSpiderRaceLarge = "Skyrim.esm|053477"
ChaurusReaperRace = "Skyrim.esm|0A5601"
ChaurusRace = "Skyrim.esm|0131EB"
DLC1ChaurusHunterRace = "Dawnguard.esm|0051FB"
DLC1_BF_ChaurusRace = "Dawnguard.esm|015136"
DLC2ExpSpiderBaseRace = "Dragonborn.esm|014449"
DLC2ExpSpiderPackmuleRace = "Dragonborn.esm|027483"
DLC2AshHopperRace = "Dragonborn.esm|01B658"
IcewraithRace = "Skyrim.esm|0131FE"
MammothRace = "Skyrim.esm|0131FF"
GiantRace = "Skyrim.esm|0131F9"


[keywords]
UndeadKeyword = "Skyrim.esm|013796"
DwemerKeyword = "Skyrim.esm|01397A"
DragonKeyword = "Skyrim.esm|035D59"
VampireKeyword = "Skyrim.esm|0A82BB"
AnimalKeyword = "Skyrim.esm|013798"
CreatureKeyword = "Skyrim.esm|013795"
BlackListKeyword = "GTS.esp|6A85AF"

DarkSouls = "Skyrim.esm|0C1E8F"
SummonUndead = "Skyrim.esm|02482B"


[containers]
Dropbox = "GTS.esp|6AD6B0"
Dropbox_Undead = "GTS.esp|6BC9BC"
Dropbox_Mechanical = "GTS.esp|6C1ABE"
Dropbox_Soul = "GTS.esp|6C1ABD"
Dropbox_Bug = "GTS.esp|6C1ABF"

[levelitems]
LootList_Master = "GTS.esp|7C3DFB"



